export const data = [
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-02-large.png',
    image: 'https://code.s3.yandex.net/react/code/bun-02.png',
    _id: '60666c42cc7b410027a1a9b1',
    name: 'Краторная булка N-200i',
    carbohydrates: 53,
    calories: 420,
    proteins: 80,
    price: 1255,
    type: 'bun',
    fat: 24,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-04-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-04-large.png',
    image: 'https://code.s3.yandex.net/react/code/meat-04.png',
    name: 'Говяжий метеорит (отбивная)',
    _id: '60666c42cc7b410027a1a9b5',
    carbohydrates: 300,
    calories: 2674,
    proteins: 800,
    type: 'main',
    price: 3000,
    fat: 800,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-01-large.png',
    image: 'https://code.s3.yandex.net/react/code/meat-01.png',
    name: 'Биокотлета из марсианской Магнолии',
    _id: '60666c42cc7b410027a1a9b6',
    carbohydrates: 242,
    calories: 4242,
    proteins: 420,
    type: 'main',
    price: 424,
    fat: 142,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-02-large.png',
    image: 'https://code.s3.yandex.net/react/code/sauce-02.png',
    _id: '60666c42cc7b410027a1a9b7',
    name: 'Соус Spicy-X',
    carbohydrates: 40,
    type: 'sauce',
    calories: 30,
    proteins: 30,
    price: 90,
    fat: 20,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-02-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-02-large.png',
    image: 'https://code.s3.yandex.net/react/code/meat-02.png',
    name: 'Мясо бессмертных моллюсков Protostomia',
    _id: '60666c42cc7b410027a1a9b4',
    carbohydrates: 33,
    calories: 420,
    proteins: 433,
    type: 'main',
    price: 1337,
    fat: 244,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-03-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-03-large.png',
    image: 'https://code.s3.yandex.net/react/code/sauce-03.png',
    name: 'Соус традиционный галактический',
    _id: '60666c42cc7b410027a1a9b9',
    carbohydrates: 42,
    type: 'sauce',
    calories: 99,
    proteins: 42,
    price: 15,
    fat: 24,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-04-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-04-large.png',
    image: 'https://code.s3.yandex.net/react/code/sauce-04.png',
    name: 'Соус фирменный Space Sauce',
    _id: '60666c42cc7b410027a1a9b8',
    carbohydrates: 11,
    type: 'sauce',
    calories: 14,
    proteins: 50,
    price: 80,
    fat: 22,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/sp_1-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sp_1-large.png',
    image: 'https://code.s3.yandex.net/react/code/sp_1.png',
    name: 'Плоды Фалленианского дерева',
    _id: '60666c42cc7b410027a1a9bc',
    carbohydrates: 55,
    calories: 77,
    proteins: 20,
    type: 'main',
    price: 874,
    __v: 0,
    fat: 5,
  },
  {
    image_mobile:
      'https://code.s3.yandex.net/react/code/mineral_rings-mobile.png',
    image_large:
      'https://code.s3.yandex.net/react/code/mineral_rings-large.png',
    image: 'https://code.s3.yandex.net/react/code/mineral_rings.png',
    name: 'Хрустящие минеральные кольца',
    _id: '60666c42cc7b410027a1a9bb',
    carbohydrates: 609,
    calories: 986,
    proteins: 808,
    type: 'main',
    price: 300,
    fat: 689,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/sauce-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/sauce-01-large.png',
    image: 'https://code.s3.yandex.net/react/code/sauce-01.png',
    name: 'Соус с шипами Антарианского плоскоходца',
    _id: '60666c42cc7b410027a1a9ba',
    carbohydrates: 100,
    calories: 100,
    proteins: 101,
    type: 'sauce',
    price: 88,
    fat: 99,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/core-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/core-large.png',
    image: 'https://code.s3.yandex.net/react/code/core.png',
    name: 'Кристаллы марсианских альфа-сахаридов',
    _id: '60666c42cc7b410027a1a9bd',
    carbohydrates: 111,
    calories: 189,
    proteins: 234,
    type: 'main',
    price: 762,
    fat: 432,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/salad-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/salad-large.png',
    image: 'https://code.s3.yandex.net/react/code/salad.png',
    name: 'Мини-салат Экзо-Плантаго',
    _id: '60666c42cc7b410027a1a9be',
    carbohydrates: 3,
    type: 'main',
    calories: 6,
    price: 4400,
    proteins: 1,
    __v: 0,
    fat: 2,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/meat-03-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/meat-03-large.png',
    image: 'https://code.s3.yandex.net/react/code/meat-03.png',
    name: 'Филе Люминесцентного тетраодонтимформа',
    _id: '60666c42cc7b410027a1a9b3',
    carbohydrates: 85,
    calories: 643,
    proteins: 44,
    type: 'main',
    price: 988,
    fat: 26,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/cheese-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/cheese-large.png',
    image: 'https://code.s3.yandex.net/react/code/cheese.png',
    name: 'Сыр с астероидной плесенью',
    _id: '60666c42cc7b410027a1a9bf',
    carbohydrates: 420,
    calories: 3377,
    proteins: 84,
    type: 'main',
    price: 4142,
    fat: 48,
    __v: 0,
  },
  {
    image_mobile: 'https://code.s3.yandex.net/react/code/bun-01-mobile.png',
    image_large: 'https://code.s3.yandex.net/react/code/bun-01-large.png',
    image: 'https://code.s3.yandex.net/react/code/bun-01.png',
    name: 'Флюоресцентная булка R2-D3',
    _id: '60666c42cc7b410027a1a9b2',
    carbohydrates: 85,
    calories: 643,
    proteins: 44,
    type: 'bun',
    price: 988,
    fat: 26,
    __v: 0,
  },
];
